# Generated by Django 3.1.7 on 2021-04-20 13:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featuring', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=200)),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
                ('time_valid', models.DateTimeField(auto_now_add=True)),
                ('time_arr', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
