# Generated by Django 3.1.7 on 2021-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='page_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
